name: chatapp
description: The Chat App
version: 0.0.1-dev
homepage: https://github.com/plugfox/chat
repository: https://github.com/plugfox/chat
issue_tracker: https://github.com/plugfox/chat/issues

funding:
  - https://www.buymeacoffee.com/plugfox
  - https://www.patreon.com/plugfox
  - https://boosty.to/plugfox

topics:
  - chat
  - websocket
  - cross-platform
  - reconnect
  - socket

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

#screenshots:
#  - description: 'Example of using the library.'
#    path: example.png

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: '>=3.10.1'


dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: any

  # Utils
  collection: any
  async: any
  meta: any
  path: any
  platform_info: ^4.0.2
  win32: ^5.0.5

  # Desktop
  window_manager: ^0.3.5

  # Authentication
  google_sign_in_platform_interface: ^2.4.2
  google_sign_in: ^6.1.5

  # Logger
  l: ^4.0.2

  # Transport
  ws: ^0.1.2

dev_dependencies:
  # Unit & Widget tests for Flutter
  flutter_test:
    sdk: flutter
  # Integration tests for Flutter
  integration_test:
    sdk: flutter
  #mockito: ^5.4.2

  # Linting
  flutter_lints: ^2.0.1

  # Codegen
  build_runner: ^2.4.6
  #flutter_launcher_icons: ^0.13.1
  #flutter_native_splash: ^2.3.1
  # build_verify: ^3.1.0
  pubspec_generator: '>=4.0.0 <5.0.0'
  #flutter_gen_runner: ^5.3.1


flutter:
  generate: true
  uses-material-design: true


flutter_intl:
  enabled: true
  class_name: GeneratedLocalization
  main_locale: en
  arb_dir: lib/src/common/localization
  output_dir: lib/src/common/localization/generated
  use_deferred_loading: false


#flutter_gen:
#  output: lib/src/common/constant/
#  line_length: 120