include: package:flutter_lints/flutter.yaml

# Analyzer options
analyzer:
  # Exclude files from analysis. Must be relative to the root of the package.
  exclude:
    # Build
    - "build/**"
    # Tests
    - "test/**.mocks.dart"
    - ".test_coverage.dart"
    - "coverage/**"
    # Assets
    - "assets/**"
    # Generated
    - "lib/src/common/localization/generated/**"
    - "lib/src/common/constants/pubspec.yaml.g.dart"
    - "lib/src/common/model/generated/**"
    - "**.g.dart"
    - "**.gql.dart"
    - "**.freezed.dart"
    - "**.config.dart"
    - "**.mocks.dart"
    - "**.gen.dart"
    - "**.pb.dart"
    - "**.pbenum.dart"
    - "**.pbjson.dart"
    # Flutter Version Manager
    - ".fvm/**"
    # Tools
    #- "tool/**"
    - "scripts/**"
    - ".dart_tool/**"
    # Platform
    - "ios/**"
    - "android/**"
    - "web/**"
    - "macos/**"
    - "windows/**"
    - "linux/**"


  # Enable the following options to enable strong mode.
  language:
    strict-casts: true
    strict-raw-types: true
    strict-inference: true

  # Enable the following options to enable new language features.
  #enable-experiment:
  #  - patterns
  #  - sealed-class
  #  - records
  #  - class-modifiers
  #  - macros
  #  - const-functions
  #  - extension-types
  #  - inference-update-2
  #  - inline-class
  #  - value-class
  #  - variance

  # Set the following options to true to enable additional analysis.
  errors:
    # Info
    directives_ordering: info
    always_declare_return_types: info

    # Warning
    unsafe_html: warning
    no_logic_in_create_state: warning
    empty_catches: warning
    close_sinks: warning

    # Error
    always_use_package_imports: error
    avoid_relative_lib_imports: error
    avoid_slow_async_io: error
    avoid_types_as_parameter_names: error
    cancel_subscriptions: error
    valid_regexps: error
    always_require_non_null_named_parameters: error

    # Disable rules

# Lint rules
linter:
  rules:
    # Public packages
    public_member_api_docs: false
    lines_longer_than_80_chars: false

    # Enabling rules
    always_use_package_imports: true
    avoid_relative_lib_imports: true

    # Disable rules
    sort_pub_dependencies: false
    prefer_relative_imports: false
    curly_braces_in_flow_control_structures: false