name: chat_authentication
description: FaaS Authentication for Chat App
version: 0.0.1-dev
homepage: https://github.com/plugfox/chat
repository: https://github.com/plugfox/chat
issue_tracker: https://github.com/plugfox/chat/issues

funding:
  - https://www.buymeacoffee.com/plugfox
  - https://www.patreon.com/plugfox
  - https://boosty.to/plugfox

topics:
  - chat
  - websocket
  - cross-platform
  - reconnect
  - socket

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

#screenshots:
#  - description: 'Example of using the library.'
#    path: example.png

environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  # HTTP Server
  functions_framework: ^0.4.3
  shelf: ^1.4.1

  # Logger
  l: ^4.0.2


dev_dependencies:
  # Testing
  test: ^1.24.4
  #mockito: ^5.4.2
  #test_process: ^2.1.0

  # Linting
  lints: ^2.1.1

  # Codegen
  build_runner: ^2.4.6
  #build_verify: ^3.1.0
  functions_framework_builder: ^0.4.10